### ISSUE TITLE
seam-cli 0.0.56 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [seamapi/seam-cli#156]
👋 trying to upgrade the formula to the latest, but ran into some regression test failure as below:

```diff
==> /opt/homebrew/Cellar/seam/0.0.56/bin/seam config set fake-server
Server URL set to https://1d334a04c0.fakeseamconnect.seam.vc
PAT set to use fakeseamconnect with "seam_apikey1_token"
==> /opt/homebrew/Cellar/seam/0.0.56/bin/seam -y health get_health
/opt/homebrew/Library/Homebrew/ignorable.rb:27:in `block in raise'
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1,12 @@
-"I’m one with the Force. The Force is with me."
+"CLI Error: Error: No possible commands
+Error: No possible commands
+    at /opt/homebrew/Cellar/seam/0.0.56/libexec/lib/node_modules/seam-cli/dist/cli.cjs:17231:13
+    at Generator.next (<anonymous>)
+    at /opt/homebrew/Cellar/seam/0.0.56/libexec/lib/node_modules/seam-cli/dist/cli.cjs:63:61
+    at new Promise (<anonymous>)
+    at __async (/opt/homebrew/Cellar/seam/0.0.56/libexec/lib/node_modules/seam-cli/dist/cli.cjs:47:10)
+    at interactForCommandSelection (/opt/homebrew/Cellar/seam/0.0.56/libexec/lib/node_modules/seam-cli/dist/cli.cjs:17215:10)
+    at /opt/homebrew/Cellar/seam/0.0.56/libexec/lib/node_modules/seam-cli/dist/cli.cjs:19018:35
+    at Generator.next (<anonymous>)
+    at fulfilled (/opt/homebrew/Cellar/seam/0.0.56/libexec/lib/node_modules/seam-cli/dist/cli.cjs:50:24)
+"
```

Need some pointer whether that is desired (I did not find any related changes)

relates to https://github.com/Homebrew/homebrew-core/pull/171777

**Comment by kainpets** [comment]
@chenrui333 Hopefully this is solved with https://github.com/Homebrew/homebrew-core/pull/174561  Thank you for letting us know!
